title: Martin Buberl
author: Martin Buberl
highlighter: rouge
permalink: /blog/:title/
url: https://martinbuberl.com
github: https://github.com/martinbuberl/martinbuberl.github.io/
twitter: martinbuberl
markdown: kramdown
gems:
  - jekyll-redirect-from
