title: Martin Buberl
author: Martin Buberl
highlighter: rouge
permalink: /blog/:title/
url: https://martinbuberl.com
repository: https://github.com/martinbuberl/martinbuberl.com
twitter: martinbuberl
markdown: kramdown
gems:
  - jekyll-redirect-from
