title: Martin Buberl
author: Martin Buberl
highlighter: rouge
permalink: /blog/:title/
url: https://martinbuberl.com
repository: martinbuberl/martinbuberl.com
twitter: martinbuberl
markdown: kramdown
plugins:
  - jekyll-redirect-from
